platform :osx, '10.7'

pod 'MASShortcut'
pod 'DBPrefsWindowController', :podspec => 'Podspecs/DBPrefsWindowController/DBPrefsWindowController.podspec'
pod 'SPMediaKeyTap', :podspec => 'Podspecs/SPMediaKeyTap/SPMediaKeyTap.podspec'
pod 'INAppStoreWindow'
pod 'AFNetworking', '1.0RC2'
pod 'INKeychainAccess'
pod 'HIDRemoteSDK', :podspec => 'Podspecs/HIDRemoteSDK/HIDRemoteSDK.podspec'
pod 'OEGridView', :podspec => 'Podspecs/OEGridView/OEGridView.podspec'
